version: '3.0'
services:
  php:
    build:
      args:
        - user=cong
        - uid=1000
      context: .
      dockerfile: Dockerfile-php
    image: php
    depends_on:
      - db
      - redis
    container_name: php
    restart: unless-stopped
    ports:
      - "1234:1234"
    volumes:
      - ./:/var/www
    networks:
      - laravel-net

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - db
    volumes:
      # - ./source:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - laravel-net

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - laravel-net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    depends_on:
      - db
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - laravel-net
    volumes:
      - cache:/data

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - laravel-net

  scheduler:
    image: php
    container_name: scheduler
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - laravel-net
    command: php artisan schedule:work

networks:
  laravel-net:
    driver: bridge

volumes:
  cache:
    driver: local
  mysql:
    driver: local
